#! /usr/bin/env python3

import sys
import igpay

def split(line):
    splitArr = []
    currentWord = ""

    for c in line:
        currentWord = currentWord + c
        if not c.isalpha():
            splitArr.append(currentWord)
            currentWord = ""
    return splitArr

# open the file for read
f = open(sys.argv[1], 'r')

for line in f:
    line = line[0:-1]
    for word in split(line):
        # This last char will save whatever is after the word, a splac, tab, puctuation, etc.
        lastChar = word[-1]
        word = word[0: -1]

        igpayReturned = igpay.igpay(word)
        igpayReturned = igpayReturned + lastChar
        print(igpayReturned, end="")
    #Print a newline
    print("")

f.close()