# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'school_Scheduler.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(830, 442)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(0, -10, 191, 431))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.AddCourse = QtGui.QWidget()
        self.AddCourse.setObjectName(_fromUtf8("AddCourse"))
        self.scrollArea = QtGui.QScrollArea(self.AddCourse)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 191, 391))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 176, 389))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.AddCourseButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.AddCourseButton.setGeometry(QtCore.QRect(0, 0, 161, 29))
        self.AddCourseButton.setFlat(False)
        self.AddCourseButton.setObjectName(_fromUtf8("AddCourseButton"))
        self.CourseTitle_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.CourseTitle_2.setGeometry(QtCore.QRect(30, 50, 113, 29))
        self.CourseTitle_2.setObjectName(_fromUtf8("CourseTitle_2"))
        self.CourseTitle = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.CourseTitle.setGeometry(QtCore.QRect(10, 30, 81, 17))
        self.CourseTitle.setObjectName(_fromUtf8("CourseTitle"))
        self.CourseTime = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.CourseTime.setGeometry(QtCore.QRect(10, 100, 71, 17))
        self.CourseTime.setObjectName(_fromUtf8("CourseTime"))
        self.CourseTimeStart = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.CourseTimeStart.setGeometry(QtCore.QRect(30, 140, 118, 29))
        self.CourseTimeStart.setObjectName(_fromUtf8("CourseTimeStart"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, 120, 56, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 56, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.CourseTimeEnd = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.CourseTimeEnd.setGeometry(QtCore.QRect(30, 200, 118, 29))
        self.CourseTimeEnd.setObjectName(_fromUtf8("CourseTimeEnd"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 56, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.CourseLocation = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.CourseLocation.setGeometry(QtCore.QRect(30, 270, 113, 29))
        self.CourseLocation.setObjectName(_fromUtf8("CourseLocation"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 310, 56, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.CheckBockMWF = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.CheckBockMWF.setGeometry(QtCore.QRect(40, 330, 88, 22))
        self.CheckBockMWF.setObjectName(_fromUtf8("CheckBockMWF"))
        self.CheckBoxTTH = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.CheckBoxTTH.setGeometry(QtCore.QRect(40, 360, 88, 22))
        self.CheckBoxTTH.setObjectName(_fromUtf8("CheckBoxTTH"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.AddCourse, _fromUtf8(""))
        self.AddAssignment = QtGui.QWidget()
        self.AddAssignment.setObjectName(_fromUtf8("AddAssignment"))
        self.label_8 = QtGui.QLabel(self.AddAssignment)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 56, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.AssignmentTitle = QtGui.QLineEdit(self.AddAssignment)
        self.AssignmentTitle.setGeometry(QtCore.QRect(50, 80, 113, 29))
        self.AssignmentTitle.setObjectName(_fromUtf8("AssignmentTitle"))
        self.label_9 = QtGui.QLabel(self.AddAssignment)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 56, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.CoursesComboBox = QtGui.QComboBox(self.AddAssignment)
        self.CoursesComboBox.setGeometry(QtCore.QRect(50, 160, 121, 25))
        self.CoursesComboBox.setObjectName(_fromUtf8("CoursesComboBox"))
        self.label_10 = QtGui.QLabel(self.AddAssignment)
        self.label_10.setGeometry(QtCore.QRect(10, 200, 56, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.CourseDateTimeEdit = QtGui.QDateTimeEdit(self.AddAssignment)
        self.CourseDateTimeEdit.setGeometry(QtCore.QRect(50, 230, 131, 29))
        self.CourseDateTimeEdit.setObjectName(_fromUtf8("CourseDateTimeEdit"))
        self.label_11 = QtGui.QLabel(self.AddAssignment)
        self.label_11.setGeometry(QtCore.QRect(10, 270, 111, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.AssignmentPercentComplete = QtGui.QSpinBox(self.AddAssignment)
        self.AssignmentPercentComplete.setGeometry(QtCore.QRect(90, 290, 60, 29))
        self.AssignmentPercentComplete.setObjectName(_fromUtf8("AssignmentPercentComplete"))
        self.label_12 = QtGui.QLabel(self.AddAssignment)
        self.label_12.setGeometry(QtCore.QRect(160, 290, 56, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.AddAssignmentButton = QtGui.QPushButton(self.AddAssignment)
        self.AddAssignmentButton.setGeometry(QtCore.QRect(0, 0, 171, 29))
        self.AddAssignmentButton.setObjectName(_fromUtf8("AddAssignmentButton"))
        self.tabWidget.addTab(self.AddAssignment, _fromUtf8(""))
        self.NotificationList = QtGui.QListView(self.dockWidgetContents)
        self.NotificationList.setGeometry(QtCore.QRect(610, 30, 191, 381))
        self.NotificationList.setObjectName(_fromUtf8("NotificationList"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(620, 0, 101, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.MondayCourses = QtGui.QListWidget(self.dockWidgetContents)
        self.MondayCourses.setGeometry(QtCore.QRect(190, 50, 81, 371))
        self.MondayCourses.setObjectName(_fromUtf8("MondayCourses"))
        self.TuesdayCourses = QtGui.QListWidget(self.dockWidgetContents)
        self.TuesdayCourses.setGeometry(QtCore.QRect(270, 50, 81, 371))
        self.TuesdayCourses.setObjectName(_fromUtf8("TuesdayCourses"))
        self.WednesdayCourses = QtGui.QListWidget(self.dockWidgetContents)
        self.WednesdayCourses.setGeometry(QtCore.QRect(350, 50, 91, 371))
        self.WednesdayCourses.setObjectName(_fromUtf8("WednesdayCourses"))
        self.ThursdayCourses = QtGui.QListWidget(self.dockWidgetContents)
        self.ThursdayCourses.setGeometry(QtCore.QRect(440, 50, 81, 371))
        self.ThursdayCourses.setObjectName(_fromUtf8("ThursdayCourses"))
        self.FridayCourses = QtGui.QListWidget(self.dockWidgetContents)
        self.FridayCourses.setGeometry(QtCore.QRect(520, 50, 81, 371))
        self.FridayCourses.setObjectName(_fromUtf8("FridayCourses"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 56, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(280, 20, 56, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_13 = QtGui.QLabel(self.dockWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(360, 20, 71, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.dockWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(450, 20, 56, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.dockWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(540, 20, 56, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.AddCourseButton.setText(_translate("DockWidget", "Add Course", None))
        self.CourseTitle_2.setText(_translate("DockWidget", "Title", None))
        self.CourseTitle.setText(_translate("DockWidget", "Course Title", None))
        self.CourseTime.setText(_translate("DockWidget", "Time", None))
        self.label.setText(_translate("DockWidget", "Start", None))
        self.label_4.setText(_translate("DockWidget", "End", None))
        self.label_5.setText(_translate("DockWidget", "Location", None))
        self.label_6.setText(_translate("DockWidget", "Days", None))
        self.CheckBockMWF.setText(_translate("DockWidget", "M, W, F", None))
        self.CheckBoxTTH.setText(_translate("DockWidget", "T, TH", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddCourse), _translate("DockWidget", "Add Course", None))
        self.label_8.setText(_translate("DockWidget", "Title", None))
        self.label_9.setText(_translate("DockWidget", "Course", None))
        self.label_10.setText(_translate("DockWidget", "Due Date", None))
        self.label_11.setText(_translate("DockWidget", "Percent Complete", None))
        self.label_12.setText(_translate("DockWidget", "%", None))
        self.AddAssignmentButton.setText(_translate("DockWidget", "Add Assignment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AddAssignment), _translate("DockWidget", "Add Assignment", None))
        self.label_7.setText(_translate("DockWidget", "Notifications", None))
        self.label_2.setText(_translate("DockWidget", "Monday", None))
        self.label_3.setText(_translate("DockWidget", "Tuesday", None))
        self.label_13.setText(_translate("DockWidget", "Wednesday", None))
        self.label_14.setText(_translate("DockWidget", "Thursday", None))
        self.label_15.setText(_translate("DockWidget", "Friday", None))

